### ISSUE TITLE
Please don't attempt "work=" by default

### ISSUE THREAD

**Issue by smuckola** [CurbSafeCharmer/refill#12]
(copied in from the Talk page on Wikipedia) I used the test version at your suggestion, and it's still doing "work=YouTube" and it's also doing "work=twitter", which is the same problem. And worse, it presumptuously tries to add "work=" to everything. A website is not automatically a work, but a delivery method for use with "via=", if anything, which it still shouldn't do without an optional checkbox. It can't discern that automatically either, and there's no need for it to try. So now I must have a "sed" command to remove all the "work=". Thanks.

**Comment by zhaofengli** [comment]
I've disabled `usedomainaswork` by default with zhaofengli/refill-labsconf@b9a1769. In addition, the `via=` parameter should now work for YouTube (fixed with f561ce18c734d876aa84648d770d22b4d37c858e). I'm working to extend the functionality to other sites.

**Comment by CurbSafeCharmer** [comment]
reFill2 no longer has this behaviour. Closing.
