### ISSUE TITLE
Create metadata from existing Wayback link

### ISSUE THREAD

**Issue by smuckola** [CurbSafeCharmer/refill#20]
I was totally wrong about this, and I missed seeing the fact that it does create archivedate=. ;)  So delete this.
.......

If we have an existing wayback machine link, such as in this:
https://en.wikipedia.org/w/index.php?title=Holographic_Versatile_Disc&diff=696533445&oldid=696505938

... Refill parses that and generates the url= parameter and fetches the title= parameter, but it doesn't generate the archivedate= parameter.  It could simply generate that from the existing archiveurl= parameter. As a bonus, it could generate a blank "deadurl=" for the user to verify. Xiexie.

**Comment by CurbSafeCharmer** [comment]
Closing, per request.
