### ISSUE TITLE
Access needed to commit localisation updates

### ISSUE THREAD

**Issue by siebrand** [CurbSafeCharmer/refill#22]
@nikerabbit and @siebrand need push access to be able to push localisation updates from translatewiki.net.

**Comment by zhaofengli** [comment]
Done! Many thanks for your help. I'll update the documentations as soon as the integration is in place.

**Comment by zhaofengli** [comment]
By the way, the `qqq` messages need to be amended, too.

**Comment by siebrand** [comment]
Will you be updating the translator documentation/qqq?

**Comment by zhaofengli** [comment]
Yes, I will. Will Translatewiki automatically pick up my changes in the repo?

**Comment by siebrand** [comment]
Yes, changes will be picked up automatically.

**Comment by CurbSafeCharmer** [comment]
This appears to have been resolved? Closing.
