### ISSUE TITLE
Blank results page - when reFilling DePaul University article

### ISSUE THREAD

**Issue by jonpatterns** [CurbSafeCharmer/refill#25]
I tried to reFill the article `https://en.wikipedia.org/wiki/DePaul_University`

However the results page is blank, and the web console gives the following error-

_The character encoding of the HTML document was not declared. The document will render with
garbled text in some browser configurations if the document contains characters from outside the
US-ASCII range. The character encoding of the page must be declared in the document or in the 
transfer protocol._

Other pages I have tried work fine. So I wonder if its something specific to the article that is causing a problem.

**Comment by zhaofengli** [comment]
May be related to [this problem](https://en.wikipedia.org/wiki/User_talk:Zhaofeng_Li/reFill#Blank_results_page), which has been fixed.  More details would be needed to confirm, though.

**Comment by CurbSafeCharmer** [comment]
Cannot reproduce; presumed fixed.
