### ISSUE TITLE
Embedded {{webarchive}} in {{cite}}

### ISSUE THREAD

**Issue by greencardamom** [CurbSafeCharmer/refill#35]
Hi zhaofengli,

Diff at line #65

https://en.wikipedia.org/w/index.php?title=Influenza_research&type=revision&diff=775432511&oldid=775163298

It inserted a {{webarchive}} into the middle of a {{cite web}} which creates a red error on rendering. It also changed the "|" to "-" in the webarchive template. 

Merging a {{webarchive}} into a {{cite web}} can be complicated. If you want to work on it I can help provide information on what kind of data to expect. There are around 150,000 {{webarchive}} and growing so it is a common occurrence. An alternative is refill skip processing any that contain a {{webarchive}}.

**Comment by greencardamom** [comment]
The template history: {{wayback}} and {{webcite}} used to be the main template use for linking to archive's outside a {{cite web}}. But we started adding many more archive services so it was decided to merge them into a single template {{webarchive}} which works for any archive service (archive.is, etc..). I'm the author of {{webarchive}} a Lua module. It's being copied over to other language wikis but {{wayback}} is also still commonly used on other languages.

**Comment by zhaofengli** [comment]
I've been working on a rewrite of the tool for the past few days, and this would be very nice to have. Could you provide more test cases and what reFill is supposed to output?

**Comment by greencardamom** [comment]
{{webarchive}} has options so best to see the documentation page and the testcases page to see how it works and what it does. In 98% of cases it will be just two to three arguments either {{webarchive |url=..|date=..}} or the addition of a |title= argument. The url would simply be moved into the |archiveurl and date into |archivedate of the {{cite web}}. 

There are exceptions: if it contains {{webarchive |date=*}}  date contains a "*" then a merger can't be done because CS1|2 doesn't support * for dates but {{webarchive}} does. If the {{webarchive}} contains |format= then merger can't be done because the format option has no equivalent in {{cite web}}. If the {{webarchive}} contains url2= through url10= then merger can't be done as CS1|2 doesn't support more than 1 archive URL but {{webarchive}} does.

**Comment by greencardamom** [comment]
Hi - this problem is still occurring on a regular basis. Another example

Diff at line #354

https://en.wikipedia.org/w/index.php?title=African-American_history&type=revision&diff=797676284&oldid=797213941

**Comment by CurbSafeCharmer** [comment]
A test of the original snippet from the influenza research article and Fox News controversies article at https://en.wikipedia.org/w/index.php?title=User:Curb_Safe_Charmer/refilltest2 indicates that reFill2 doesn't alter {{webarchive}} tags in the way that the original reFill did. Closing.
