### ISSUE TITLE
Follow redirects like reflinks

### ISSUE THREAD

**Issue by Artoria2e5** [CurbSafeCharmer/refill#37]
Refill does not like following redirects like reflinks does. Might have something to do with #32 too.

**Comment by zhaofengli** [comment]
Could you give an example of this?

**Comment by Artoria2e5** [comment]
Oops, reflinks does not follow page redirects. Take it as a simple feature request I guess.

Use enwp page "Bush, George W" for testing.

**Comment by zhaofengli** [comment]
Ah, you mean MediaWiki redirects. This will be fixed on reFill 2.

**Comment by CurbSafeCharmer** [comment]
I believe this is fixed in refill2. Closing.
