### ISSUE TITLE
problem reFilling cd (command)

### ISSUE THREAD

**Issue by danielbrownmsm** [CurbSafeCharmer/refill#61]
The tool seems to run into issues trying to fix [cd (command)](https://en.wikipedia.org/wiki/Cd_(command)). Have tried multiple times, get the same result. It sits there for a while fixing stuff and then stops 3/4 the way through and says that "an error has occurred." Just thought I'd put this out there. Not sure why, but the tool also doesn't seem to expand references that are named (e.g. if there's a 

`<ref name="example">[www.example.com Example.com]</ref>`

it won't try to expand it.)

**Comment by CurbSafeCharmer** [comment]
Cannot reproduce. Page history shows ReFill has successfully been used on this article. Probably your attempt coincided with the tool being down.
