### ISSUE TITLE
Update bug report link

### ISSUE THREAD

**Issue by NovemLinguae** [CurbSafeCharmer/refill#97]
Currently targets:
https://en.wikipedia.org/wiki/User_talk:Zhaofeng_Li

Suggested new target:
https://github.com/CurbSafeCharmer/refill/issues

![2021-12-12_080930](https://user-images.githubusercontent.com/79697282/145719957-0d519c28-50c0-4690-b33d-d98762f8004b.png)

**Comment by CurbSafeCharmer** [comment]
Updated in web/src/App.vue on Nov 9, 2021 in this commit: https://github.com/CurbSafeCharmer/refill/commit/534cf9e3772e66d51a182671f32c531657c031c0#diff-7322e6842f92edbe4a6e810d63f066ec95e64806d64a02b52e2b9bef2a73db91
